// numstr.cpp -- following number input with line input
#include <iostream>
int main()
{
    using namespace std;
    cout << "What year was your house built?" << endl;
    int year;
    cin >> year;
    cin.get(); // cin.get(ch);

    // (cin >> year).get(); // or (cin >> year).get(ch);
    cout << "What is its street address?\n";
    // The problem is that when cin
    // reads the year, it leaves the newline generated by the Enter key in the input queue.Then
    // cin.getline() reads the newline as an empty line and assigns a null string to the
    // address array.
    char address[80];
    cin.getline(address, 80);
    cout << "Year built: " << year << endl;
    cout << "Address: " << address << endl;
    cout << "Done!\n";
    return 0;
}